server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true  # ? API Gateway must register with Eureka
    fetch-registry: true  # ? API Gateway must fetch the service registry

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: orderService  # Lowercase names for consistency
          uri: http://localhost:8020
#          uri: lb://ORDERSERVICE
          predicates:
            - Path=/orders/**

        - id: ProductService
          uri: http://localhost:8040
#          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/products/**
            - Path=/sellers/**
            - Path=/cart/**

        - id: InventoryService
          uri: http://localhost:8010
#          uri: lb://INVENTORYSERVICE
          predicates:
            - Path=/inventory/**
